#!/bin/bash
set -ex
echo "===== Network Setup ======="

function res_options() {
	echo 'RES_OPTIONS="single-request-reopen"' >> /etc/sysconfig/network
}

function sshd() {
	echo "UseDNS no" >> /etc/ssh/sshd_config
	echo "GSSAPIAuthentication no" >> /etc/ssh/sshd_config
}

function configs() {
	rm -f /etc/udev/rules.d/70-persistent-net.rules
	rm -f /etc/sysconfig/network-scripts/ifcfg-eno*
	ln -sf /dev/null /etc/udev/rules.d/80-net-name-slot.rules
	sed -i '/^HWADDR/d' /etc/sysconfig/network-scripts/ifcfg-*
	sed -i "/^UUID/d" /etc/sysconfig/network-scripts/ifcfg-*
	cat <<EOF > /etc/sysconfig/network-scripts/ifcfg-eth0
# Generated by packer image builder
DEVICE="eth0"
ONBOOT=yes
NETBOOT=yes
IPV6INIT=yes
BOOTPROTO=dhcp
TYPE=Ethernet
NAME="eth0"
EOF
}

function main() {
	if [[ "${PACKER_BUILDER_TYPE}" =~ "virtualbox" ]]; then
		res_options
	fi
	sshd
	configs
}

main